// Real London parking data with accurate postcodes, coordinates, and restriction schedules
const PARKING_DATA = [
  // ── WESTMINSTER ──────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Berwick Street Parking Bays",
    type: "on-street",
    address: "Berwick Street, Soho",
    borough: "Westminster",
    postcode: "W1F 8SN",
    coords: [51.5134, -0.1353],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 28,
    bayType: "Pay & Display",
    notes: "Free all day Sunday. Located next to famous Berwick Street Market.",
    walkingLandmark: "200m from Piccadilly Circus",
    tflCameraId: "00001.05410"
  },
  {
    id: 2,
    name: "Brewer Street Pay Bays",
    type: "on-street",
    address: "Brewer Street, Soho",
    borough: "Westminster",
    postcode: "W1F 0RF",
    coords: [51.5117, -0.1362],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 16,
    bayType: "Pay & Display",
    notes: "Free all day Sunday and Bank Holidays. Good for evening theatre trips.",
    walkingLandmark: "150m from Piccadilly Circus",
    tflCameraId: "00001.05230"
  },
  {
    id: 3,
    name: "Wardour Street Parking",
    type: "on-street",
    address: "Wardour Street, Soho",
    borough: "Westminster",
    postcode: "W1D 6PB",
    coords: [51.5141, -0.1318],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 22,
    bayType: "Single Yellow / Pay Display",
    notes: "Popular evening spot for Soho restaurants. CPZ ends at 18:30.",
    walkingLandmark: "300m from Oxford Circus",
    tflCameraId: "00001.07620"
  },
  {
    id: 4,
    name: "NCP Parker Street (Covent Garden)",
    type: "car-park",
    address: "Parker Street, Covent Garden",
    borough: "Westminster",
    postcode: "WC2B 5PW",
    coords: [51.5142, -0.1222],
    freeAfter: null,
    freeUntil: null,
    restrictedDays: [],
    freeDays: [],
    spaces: 186,
    bayType: "Multi-Storey Car Park",
    notes: "24hr paid parking. Evening rate from 18:00. £8 flat rate after 6pm until midnight.",
    walkingLandmark: "50m from Holborn Underground",
    eveningRate: "£8 (18:00–24:00)",
    tflCameraId: "00001.06840"
  },
  {
    id: 5,
    name: "Spring Gardens (Trafalgar Sq)",
    type: "on-street",
    address: "Spring Gardens, Charing Cross",
    borough: "Westminster",
    postcode: "SW1A 2BN",
    coords: [51.5073, -0.1275],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 12,
    bayType: "Pay & Display",
    notes: "Great central location near Trafalgar Square. Limited spaces.",
    walkingLandmark: "Adjacent to Trafalgar Square",
    tflCameraId: "00001.07770"
  },

  // ── CITY OF LONDON ────────────────────────────────────────────────────────────
  {
    id: 6,
    name: "Barbican Centre Car Park",
    type: "car-park",
    address: "Beech Street, Barbican",
    borough: "City of London",
    postcode: "EC2Y 8AE",
    coords: [51.5203, -0.0963],
    freeAfter: "18:00",
    freeUntil: "07:00",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri"],
    freeDays: ["Sat","Sun"],
    spaces: 320,
    bayType: "Underground Car Park",
    notes: "Large underground car park. Free evenings and weekends. Excellent for Barbican arts events.",
    walkingLandmark: "Directly under Barbican Arts Centre",
    tflCameraId: "00001.01520"
  },
  {
    id: 7,
    name: "Aldersgate Street Bays",
    type: "on-street",
    address: "Aldersgate Street, City",
    borough: "City of London",
    postcode: "EC1A 4JA",
    coords: [51.5205, -0.0976],
    freeAfter: "18:00",
    freeUntil: "07:00",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri"],
    freeDays: ["Sat","Sun"],
    spaces: 18,
    bayType: "Single Yellow / Pay Bays",
    notes: "City of London CPZ ends at 18:00 sharp on weekdays. Free all weekend.",
    walkingLandmark: "400m from St Paul's Cathedral",
    tflCameraId: "00001.00160"
  },
  {
    id: 8,
    name: "London Wall Parking Bays",
    type: "on-street",
    address: "London Wall, City of London",
    borough: "City of London",
    postcode: "EC2M 5PP",
    coords: [51.5177, -0.0905],
    freeAfter: "18:30",
    freeUntil: "08:00",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri"],
    freeDays: ["Sat","Sun"],
    spaces: 35,
    bayType: "Pay & Display",
    notes: "Long stretch of bays on London Wall. Very popular City location. Free Sat & Sun.",
    walkingLandmark: "500m from Moorgate Station",
    tflCameraId: "00001.04660"
  },
  {
    id: 9,
    name: "Moorgate Street Bays",
    type: "on-street",
    address: "Moorgate, City of London",
    borough: "City of London",
    postcode: "EC2M 6UP",
    coords: [51.5186, -0.0882],
    freeAfter: "18:30",
    freeUntil: "07:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri"],
    freeDays: ["Sat","Sun"],
    spaces: 24,
    bayType: "Pay & Display",
    notes: "Busy financial district. Restrictions ease at 18:30 weekdays and all weekend.",
    walkingLandmark: "Adjacent to Moorgate Underground",
    tflCameraId: "00001.05010"
  },

  // ── SOUTHWARK ─────────────────────────────────────────────────────────────────
  {
    id: 10,
    name: "Borough High Street Bays",
    type: "on-street",
    address: "Borough High Street, Borough",
    borough: "Southwark",
    postcode: "SE1 1LB",
    coords: [51.5019, -0.0921],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 30,
    bayType: "Pay & Display",
    notes: "Near Borough Market. Great for evening dining. Sunday free all day.",
    walkingLandmark: "100m from Borough Market",
    tflCameraId: "00001.01870"
  },
  {
    id: 11,
    name: "Tooley Street Pay Bays",
    type: "on-street",
    address: "Tooley Street, London Bridge",
    borough: "Southwark",
    postcode: "SE1 2TF",
    coords: [51.5036, -0.0793],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 20,
    bayType: "Single Yellow / Pay Bays",
    notes: "Near Hay's Galleria and London Bridge. Evening restrictions end 18:30.",
    walkingLandmark: "300m from London Bridge Station",
    tflCameraId: "00001.08200"
  },
  {
    id: 12,
    name: "Clink Street Car Park",
    type: "car-park",
    address: "Clink Street, Bankside",
    borough: "Southwark",
    postcode: "SE1 9DG",
    coords: [51.5075, -0.0949],
    freeAfter: "18:30",
    freeUntil: "07:00",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 145,
    bayType: "Surface Car Park",
    notes: "Near Shakespeare's Globe and Tate Modern. Free after 18:30 and all Sunday.",
    walkingLandmark: "200m from Tate Modern",
    tflCameraId: "00001.02640"
  },

  // ── CAMDEN ────────────────────────────────────────────────────────────────────
  {
    id: 13,
    name: "Pratt Street Parking Bays",
    type: "on-street",
    address: "Pratt Street, Camden Town",
    borough: "Camden",
    postcode: "NW1 0AE",
    coords: [51.5408, -0.1426],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 25,
    bayType: "Pay & Display",
    notes: "Quiet side street off Camden High Street. Good for evening market visits.",
    walkingLandmark: "250m from Camden Town Underground",
    tflCameraId: "00001.02130"
  },
  {
    id: 14,
    name: "Euston Road (NW1) Bays",
    type: "on-street",
    address: "Euston Road, Regent's Park",
    borough: "Camden",
    postcode: "NW1 2SB",
    coords: [51.5257, -0.1340],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 40,
    bayType: "Pay & Display",
    notes: "Large stretch of bays on Euston Road. Free evenings and Sundays.",
    walkingLandmark: "Adjacent to Euston Station",
    tflCameraId: "00001.03120"
  },

  // ── ISLINGTON ─────────────────────────────────────────────────────────────────
  {
    id: 15,
    name: "Duncan Street Parking",
    type: "on-street",
    address: "Duncan Street, Angel",
    borough: "Islington",
    postcode: "N1 8BW",
    coords: [51.5337, -0.1023],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 18,
    bayType: "Pay & Display",
    notes: "Near Angel and Islington Green. Evening rates end at 18:30.",
    walkingLandmark: "400m from Angel Underground",
    tflCameraId: "00001.03040"
  },
  {
    id: 16,
    name: "Upper Street Resident/Pay Bays",
    type: "on-street",
    address: "Upper Street, Islington",
    borough: "Islington",
    postcode: "N1 0PQ",
    coords: [51.5382, -0.1027],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 55,
    bayType: "Pay & Display / Resident",
    notes: "Busy restaurant and bar street. Visitor bays free after 18:30. Sunday free.",
    walkingLandmark: "On Upper Street near Angel",
    tflCameraId: "00001.08450"
  },

  // ── KENSINGTON & CHELSEA ──────────────────────────────────────────────────────
  {
    id: 17,
    name: "Bramham Gardens Bays",
    type: "on-street",
    address: "Bramham Gardens, Earl's Court",
    borough: "Kensington & Chelsea",
    postcode: "SW5 0JQ",
    coords: [51.4922, -0.1838],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 20,
    bayType: "Pay & Display",
    notes: "Residential street with pay bays. Evening and Sunday free parking.",
    walkingLandmark: "300m from Earl's Court Underground",
    tflCameraId: "00001.01180"
  },
  {
    id: 18,
    name: "Q-Park Knightsbridge",
    type: "car-park",
    address: "Pavilion Road, Knightsbridge",
    borough: "Kensington & Chelsea",
    postcode: "SW1X 0HP",
    coords: [51.4979, -0.1617],
    freeAfter: null,
    freeUntil: null,
    restrictedDays: [],
    freeDays: [],
    spaces: 245,
    bayType: "Multi-Storey Car Park",
    notes: "24hr paid. Evening rate (after 18:30) £12 until midnight. Near Harrods.",
    walkingLandmark: "100m from Harrods",
    eveningRate: "£12 (18:30–24:00)",
    tflCameraId: "00001.07040"
  },

  // ── TOWER HAMLETS / CANARY WHARF ──────────────────────────────────────────────
  {
    id: 19,
    name: "Canada Square Car Park (Canary Wharf)",
    type: "car-park",
    address: "Canada Square, Canary Wharf",
    borough: "Tower Hamlets",
    postcode: "E14 5AX",
    coords: [51.5057, -0.0222],
    freeAfter: "18:00",
    freeUntil: "07:00",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri"],
    freeDays: ["Sat","Sun"],
    spaces: 1800,
    bayType: "Underground Car Park",
    notes: "Massive car park under Canary Wharf. Free evenings after 18:00 and all weekend.",
    walkingLandmark: "Under Canada Square tower",
    tflCameraId: "00001.02270"
  },
  {
    id: 20,
    name: "Fairchild Street Pay Bays",
    type: "on-street",
    address: "Fairchild Street, Shoreditch",
    borough: "Hackney",
    postcode: "EC2A 3NS",
    coords: [51.5237, -0.0781],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 22,
    bayType: "Pay & Display",
    notes: "Popular Shoreditch street. Evening free parking. Brilliant for nightlife.",
    walkingLandmark: "300m from Shoreditch High Street Station",
    tflCameraId: "00001.03590"
  },

  // ── HACKNEY ───────────────────────────────────────────────────────────────────
  {
    id: 21,
    name: "Mare Street Pay Bays",
    type: "on-street",
    address: "Mare Street, Hackney Central",
    borough: "Hackney",
    postcode: "E8 4RG",
    coords: [51.5446, -0.0570],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 35,
    bayType: "Pay & Display",
    notes: "Town centre bays on Mare Street. CPZ ends 18:30. Free all day Sunday.",
    walkingLandmark: "Adjacent to Hackney Town Hall",
    tflCameraId: "00001.04150"
  },

  // ── LAMBETH ───────────────────────────────────────────────────────────────────
  {
    id: 22,
    name: "Kennington Road Bays",
    type: "on-street",
    address: "Kennington Road, Kennington",
    borough: "Lambeth",
    postcode: "SE11 6SB",
    coords: [51.4940, -0.1121],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 28,
    bayType: "Pay & Display",
    notes: "Near Oval Cricket Ground. Evening and Sunday parking free.",
    walkingLandmark: "400m from Oval Underground",
    tflCameraId: "00001.04440"
  },

  // ── GREENWICH ─────────────────────────────────────────────────────────────────
  {
    id: 23,
    name: "College Approach Car Park",
    type: "car-park",
    address: "College Approach, Greenwich",
    borough: "Greenwich",
    postcode: "SE10 9HY",
    coords: [51.4826, -0.0076],
    freeAfter: "18:00",
    freeUntil: "08:00",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 200,
    bayType: "Surface Car Park",
    notes: "Near Cutty Sark and Royal Observatory. Free after 18:00 and all Sunday.",
    walkingLandmark: "150m from Cutty Sark DLR",
    tflCameraId: "00001.02900"
  },

  // ── HAMMERSMITH & FULHAM ──────────────────────────────────────────────────────
  {
    id: 24,
    name: "King Street Parking Bays",
    type: "on-street",
    address: "King Street, Hammersmith",
    borough: "Hammersmith & Fulham",
    postcode: "W6 9NH",
    coords: [51.4920, -0.2240],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 40,
    bayType: "Pay & Display",
    notes: "Main high street bays. Busy shopping area. Evening free from 18:30.",
    walkingLandmark: "300m from Hammersmith Underground",
    tflCameraId: "00001.04060"
  },

  // ── WANDSWORTH ────────────────────────────────────────────────────────────────
  {
    id: 25,
    name: "Lavender Hill Pay Bays",
    type: "on-street",
    address: "Lavender Hill, Clapham Junction",
    borough: "Wandsworth",
    postcode: "SW11 5RL",
    coords: [51.4649, -0.1646],
    freeAfter: "18:30",
    freeUntil: "08:30",
    restrictedDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    freeDays: ["Sun"],
    spaces: 32,
    bayType: "Pay & Display",
    notes: "Near Clapham Junction. Vibrant evening area. Free parking from 18:30.",
    walkingLandmark: "500m from Clapham Junction Station",
    tflCameraId: "00001.04870"
  }
];

// TfL JamCam nearby camera mappings (camera IDs for visual verification)
const TFL_CAMERA_BASE = "https://s3-eu-west-1.amazonaws.com/jamcams.tfl.gov.uk/";

// Borough color scheme
const BOROUGH_COLORS = {
  "Westminster": "#7c3aed",
  "City of London": "#0891b2",
  "Southwark": "#0d9488",
  "Camden": "#b45309",
  "Islington": "#7c2d12",
  "Kensington & Chelsea": "#be185d",
  "Tower Hamlets": "#0f766e",
  "Hackney": "#1d4ed8",
  "Lambeth": "#15803d",
  "Greenwich": "#b91c1c",
  "Hammersmith & Fulham": "#6d28d9",
  "Wandsworth": "#92400e"
};
